# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginSystem', '0002_auto_20160607_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='url',
        ),
    ]
